import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.scss';

const inter = Inter({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-inter',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Inctagram',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): React.JSX.Element => {
    return (
        <html lang="en" className={inter.variable}>
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
