import type { Metadata } from 'next';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';

import './globals.scss';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = GeistMono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): React.JSX.Element => {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
